security:
    providers:
        userdb:
            entity:
                class: App\Entity\User
                property: username

    encoders:
        App\Entity\User:
            id: App\Security\LegacyEncoder

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/(cat|biz)_admin.php$, roles: ROLE_ADMIN }
